/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as FormsIndexRouteImport } from "./routes/_forms/index";
import { Route as FormsSignUpRouteImport } from "./routes/_forms/sign-up";
import { Route as ProtectedRouteImport } from "./routes/_protected";
import { Route as ProtectedBoardsRouteImport } from "./routes/_protected/boards";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";

const ProtectedRoute = ProtectedRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/_protected",
} as any);
const FormsIndexRoute = FormsIndexRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/_forms/",
  path: "/",
} as any);
const ProtectedBoardsRoute = ProtectedBoardsRouteImport.update({
  getParentRoute: () => ProtectedRoute,
  id: "/boards",
  path: "/boards",
} as any);
const FormsSignUpRoute = FormsSignUpRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/_forms/sign-up",
  path: "/sign-up",
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: "/api/auth/$",
  path: "/api/auth/$",
} as any);

export interface FileRoutesByFullPath {
  "/sign-up": typeof FormsSignUpRoute;
  "/boards": typeof ProtectedBoardsRoute;
  "/": typeof FormsIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
}
export interface FileRoutesByTo {
  "/sign-up": typeof FormsSignUpRoute;
  "/boards": typeof ProtectedBoardsRoute;
  "/": typeof FormsIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_protected": typeof ProtectedRouteWithChildren;
  "/_forms/sign-up": typeof FormsSignUpRoute;
  "/_protected/boards": typeof ProtectedBoardsRoute;
  "/_forms/": typeof FormsIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/sign-up" | "/boards" | "/" | "/api/auth/$";
  fileRoutesByTo: FileRoutesByTo;
  to: "/sign-up" | "/boards" | "/" | "/api/auth/$";
  id:
    | "__root__"
    | "/_protected"
    | "/_forms/sign-up"
    | "/_protected/boards"
    | "/_forms/"
    | "/api/auth/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren;
  FormsSignUpRoute: typeof FormsSignUpRoute;
  FormsIndexRoute: typeof FormsIndexRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_protected": {
      id: "/_protected";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_forms/": {
      id: "/_forms/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof FormsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_protected/boards": {
      id: "/_protected/boards";
      path: "/boards";
      fullPath: "/boards";
      preLoaderRoute: typeof ProtectedBoardsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    "/_forms/sign-up": {
      id: "/_forms/sign-up";
      path: "/sign-up";
      fullPath: "/sign-up";
      preLoaderRoute: typeof FormsSignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface ProtectedRouteChildren {
  ProtectedBoardsRoute: typeof ProtectedBoardsRoute;
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBoardsRoute: ProtectedBoardsRoute,
};

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  FormsIndexRoute: FormsIndexRoute,
  FormsSignUpRoute: FormsSignUpRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
